@baseUrl = http://localhost:3000/api/categories

### GET all public categories
GET {{baseUrl}}/allPublicCategories
Content-Type: application/json  

### GET category by ID
GET {{baseUrl}}/category/asf
Content-Type: application/json

### Create category
POST {{baseUrl}}/category
Content-Type: application/json

{
    "categoryName": "Category 1",
    "userID": "4a15d021-9564-48da-931f-45571c5aa1d0",
    "classic": "1",
    "quote": "1",
    "emoji": "0",
    "picture": "0",
    "desc": "1",
    "public": "1"
}


### GET all category
GET {{baseUrl}}/allCategory
Content-Type: application/json
Authorization: Bearer token

### Get all data for category
GET {{baseUrl}}/data/9a3c8657-92f5-43ec-ae9a-6c67ab3a2802
Content-Type: application/json
Authorization: Bearer token