@baseUrl = http://localhost:3000/api/games

### GET all classic by category ID
GET {{baseUrl}}/allClassic/asd
Content-Type: application/json


### GET classic solution by category ID
GET {{baseUrl}}/solutionClassic/asd
Content-Type: application/json


### GET all emoji by category ID
GET {{baseUrl}}/allEmoji/bkgldnblkdf
Content-Type: application/json


### GET emoji solution by category ID
GET {{baseUrl}}/solutionEmoji/bkgldnblkdf
Content-Type: application/json

### GET all description by category ID
GET {{baseUrl}}/allDescription/asf
Content-Type: application/json

###GET description solution  by category ID
GET {{baseUrl}}/solutionDescription/asf
Content-Type: application/json

### Get Leaderboard
GET {{baseUrl}}/leaderboard
Content-Type: application/json

### Get Leaderboard 1 user
GET {{baseUrl}}/leaderboard/79dd2b70-259b-48dc-bf8e-49f872df6770
Content-Type: application/json