@baseUrl = http://localhost:3000/api
@authToken = {{login.response.body.token}}

### login user
# @name login

POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "tesztelek@gmail.com",
    "passwd": "123456"
}


### register user
# @name register

POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "name": "Teszt Elek",
    "email": "tesztelek6@gmail.com",
    "password": "123456",
    "confirm": "123456"
}

### Change Password
# @name change-password

PATCH  {{baseUrl}}/users/change-password/c8bb52ba-6243-409c-b8c9-33d707aa5714
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
    "oldpasswd": "123456",
    "passwd": "newpassword123",
    "confirm": "newpassword123"
}

### Forgott password
# @name forgott-password
POST {{baseUrl}}/forgott-password
Content-Type: application/json

{
    "email": "aronbartek@gmail.com"
}

### Get all users
# @name get-all-users
GET {{baseUrl}}/users/allUsers
Content-Type: application/json
Authorization: Bearer {{authToken}}

###Get match history
GET {{baseUrl}}/users/history/588dca61-fdcd-4dc5-8b82-34a35d7ed737
Content-Type: application/json
Authorization: Bearer {{authToken}}

###Edit user by id
PATCH {{baseUrl}}/users/edit/192b5d8c-6b3a-4ca2-b492-9ce0c1a71810
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Teszt Elek",
    "email": "teszt@gmail.com",
    "role": "admin",
    "profilePic": ""
}