@baseUrl = http://localhost:3000/api
@authToken = {{login.response.body.token}}

### login user
# @name login

POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "tesztelek6@gmail.com",
    "passwd": "123456"
}


### register user
# @name register

POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "name": "Teszt Elek",
    "email": "tesztelek7@gmail.com",
    "password": "123456",
    "confirm": "123456"
}

### Change Password
# @name change-password

POST {{baseUrl}}/users/change-password/c8bb52ba-6243-409c-b8c9-33d707aa5714
Content-Type: application/json

{
    "oldpasswd": "123456",
    "passwd": "newpassword123",
    "confirm": "newpassword123"
}

### Forgott password
# @name forgott-password
POST {{baseUrl}}/forgott-password
Content-Type: application/json

{
    "email": "yourdlehelp@gmail.com"
}

### Match history

GET {{baseUrl}}/users/history/e408f0ea-02b6-4118-8b22-905afd9a5648
Content-Type: application/json
Authorization: Bearer {{authToken}}