@baseUrl = http://localhost:3000/api

### login user
# @name login

POST {{baseUrl}}/users/login
Content-Type: application/json

{
    "email": "tesztelek6@gmail.com",
    "password": "123456"
}


### register user
# @name register

POST {{baseUrl}}/users/register
Content-Type: application/json

{
    "name": "Teszt Elek",
    "email": "tesztelek6@gmail.com",
    "password": "123456",
    "confirm": "123456"
}